---
- name: Paigalda veebiserverid kui puuduvad
  hosts: webservers
  become: yes
  tasks:
    - name: Paigalda Apache (AlmaLinux / RedHat)
      dnf:
        name: httpd
        state: present
        update_cache: yes

    - name: Veendu, et Apache on käivitatud ja lubatud
      systemd:
        name: httpd
        state: started
        enabled: yes

- name: Paigalda andmebaasiserverid kui puuduvad
  hosts: dbservers
  become: yes
  tasks:
    - name: Paigalda MariaDB server (Debian/Ubuntu)
      apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Veendu, et MariaDB on käivitatud ja lubatud
      systemd:
        name: mariadb
        state: started
        enabled: yes


